apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "diabetes-ml-chart.fullname" . }}
  labels:
    {{- include "diabetes-ml-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "diabetes-ml-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "diabetes-ml-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: diabetes-ml-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP

          env:
            - name: MLFLOW_TRACKING_URI
              value: "{{ .Values.env.MLFLOW_TRACKING_URI }}"
            - name: MLFLOW_MODEL_NAME
              value: "{{ .Values.env.MLFLOW_MODEL_NAME }}"
            - name: MLFLOW_MODEL_VERSION
              value: "{{ .Values.env.MLFLOW_MODEL_VERSION }}"

          startupProbe:
            httpGet:
              path: {{ .Values.probes.startup.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.startup.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.startup.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.startup.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.startup.failureThreshold }}

          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}

          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
