apiVersion: apps/v1
kind: Deployment
metadata:
  name: diabetes-ml-service
  labels:
    app: diabetes-ml-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: diabetes-ml-service
  template:
    metadata:
      labels:
        app: diabetes-ml-service
    spec:
      containers:
        - name: diabetes-ml-service
          image: diabetes-mlservice:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000

          env:
            - name: MLFLOW_TRACKING_URI
              value: "http://158.160.228.178:5000"
            - name: MLFLOW_MODEL_NAME
              value: "diabets"
            - name: MLFLOW_MODEL_VERSION
              value: "3"

          startupProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
