apiVersion: v1
kind: Service
metadata:
  name: diabetes-ml-service
  labels:
    app: diabetes-ml-service
spec:
  type: ClusterIP
  selector:
    app: diabetes-ml-service
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
