replicaCount: 2

image:
  repository: diabetes-mlservice
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

env:
  MLFLOW_TRACKING_URI: "http://158.160.228.178:5000"
  MLFLOW_MODEL_NAME: "diabets"
  MLFLOW_MODEL_VERSION: "3"

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

probes:
  startup:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 30
  readiness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3
  liveness:
    path: /health
    initialDelaySeconds: 15
    periodSeconds: 20
    timeoutSeconds: 2
    failureThreshold: 3
